zb_redirection_url: http://10.161.0.130:2001/sensors
zb_sources:
  0013a20041531c31:
    room: cave
    format: temperature;humidity
  0013a20041531ccf:
    room: kitchen
    format: temperature;humidity
  0013a20041502662:
    room: bedroom1
    format: temperature;humidity;power
  0013a20041940680: # XB3-24Z8PT-J
    room: bedroom2
    format: temperature;humidity;power
  0013a2004193ff77: # XB3-24Z8PT-J
    room: bedroom3
    format: temperature;humidity;power
  0013a2004172cf48:
    room: house
    format: L1;L2;L3
  0013a200414f8f0c:
    room: office
    format: temperature;humidity;power
  0013a200415025db:
    room: outdoor
    format: temperature;humidity;power
  0013a20041483246:
    room: toilet1
    format: json
  0013a2004193feff: # XB3-24Z8PT-J
    room: bathroom
    format: temperature;humidity;power
  0013a2004193ff49: # XB3-24Z8PT-J
    room: piano
    format: temperature;humidity;power
  0013a20041940531: # XB3-24Z8PT-J
    room: boiler
    format: temperature;humidity;power
serial:
  name: /dev/ttyUSB0
  speed: 9600
tcp:
  port: 2003

# NOT USED
#
# XB3-24Z8PT - 0013a200418d0e57
# XB3-24Z8PT - 0013a200418d331d
# XB3-24Z8PT - 0013a200418d2be3
